### ISSUE TITLE
Full screen Blipshot bug for luddite

### ISSUE THREAD

**Issue by skillwizard** [folletto/Blipshot#18] opened 2017-10-02 11:15 UTC
Hi there, I use Blipshot a lot for work and it's suddenly not taking the whole page, just the visible. I see a thread about this but not being technical none of it or the links makes sense. How can I resolve this as a stupid person? Thanks in advance!

**Comment by folletto** [comment] 2017-10-02 11:56
Could you please add more details, for example the link to a page where it doesn't work on?

**Comment by skillwizard** [comment] 2017-10-02 12:02
Hi there, thanks, it's all webpages, it's weird, it suddenly happened. I have taken the app off and re-added and restarted, but it only saves the visible part of the page now. Any web page like this: http://www.liveforfilm.com/2017/09/29/the-25th-raindance-film-festival-competition-winners-revealed/

**Comment by folletto** [comment] 2017-10-02 12:06
Thank you. It's likely a bug related to API changes in Chrome 61. And yes, as you already found out it's likely the same issue as #17. I'm fixing it now...

**Comment by skillwizard** [comment] 2017-10-02 12:17
Amazing thanks so much

**Comment by folletto** [comment] 2017-10-02 12:52
Ok the issue is fixed in 1.2.2 and has been pushed to the Chrome Store. 
It should be automatically updated by Chrome in the next hours (I'm not sure how long it's going to take exactly).

**Closed by folletto** 2017-10-02 12:52 UTC
